name: Publish docker image on releases and prereleases

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Add safe git directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta on releases
        if: ${{ github.event_name == 'release' && github.event.action == 'released' }}
        id: meta-releases
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Build Docker Container on releases
        if: ${{ github.event_name == 'release' && github.event.action == 'released' }}
        uses: docker/build-push-action@v5
        with:
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ${{ steps.meta-releases.outputs.tags }}
          labels: ${{ steps.meta-releases.outputs.labels }}

      - name: Docker meta on prereleases
        if: ${{ github.event_name == 'release' && github.event.action == 'prereleased' }}
        id: meta-prereleases
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Build Docker Container on prereleases
        if: ${{ github.event_name == 'release' && github.event.action == 'prereleased' }}
        uses: docker/build-push-action@v5
        with:
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ${{ steps.meta-prereleases.outputs.tags }}
          labels: ${{ steps.meta-prereleases.outputs.labels }}
